#!/usr/bin/sh

# pass in server bmc mac address as only arg and get
# a key to unlock features


function supermicroKeygen () {
  echo -n $1 | \
  xxd -r -p | \
  openssl dgst -sha1 -mac HMAC -macopt hexkey:8544E3B47ECA58F9583043F8 | \
  awk '{print $2}' | \
  cut -c 1-24 | \
  fold -w4 | \
  paste -sd '-'
}

#run the function
supermicroKeygen $1
